### ISSUE TITLE
Unable to install CLI on an M1 Macbook

### ISSUE THREAD

**Issue by ambethia** [hookdeck/homebrew-hookdeck#1]
```
% brew install hookdeck/hookdeck/hookdeck
==> Tapping hookdeck/hookdeck
Cloning into '/opt/homebrew/Library/Taps/hookdeck/homebrew-hookdeck'...
remote: Enumerating objects: 33, done.
remote: Counting objects: 100% (33/33), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 33 (delta 10), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (33/33), 4.08 KiB | 2.04 MiB/s, done.
Resolving deltas: 100% (10/10), done.
Error: Invalid formula: /opt/homebrew/Library/Taps/hookdeck/homebrew-hookdeck/hookdeck.rb
formulae require at least a URL
Error: Cannot tap hookdeck/hookdeck: invalid syntax in tap!
```

It looks like you're explicitly guarding for Intel-based macs without an alternative. Help!

**Comment by ambethia** [comment]
FWIW, it seems to run fine if I [remove the guard](https://github.com/ambethia/homebrew-hookdeck/blob/master/hookdeck.rb#L11).

**Comment by mkherlakian** [comment]
Hi @ambethia! Apologies for the delay, our watches on our repos weren't configured properly and as a result I missed this issue.

I pushed an update a couple of weeks ago to address this issue, and take into account the M1 hardware: https://github.com/hookdeck/homebrew-hookdeck/blob/56dfca152a5bc7c55d5aa74d29973f5604f220c9/hookdeck.rb#L15

The link you pasted above seems to be linking to the old version that doesn't include the guard for Intel/ARM. Would it be possible for you to try updating? Or confirm if you did so we can look into it on this end to see if there was an issue with the update?

Thanks!
